### ISSUE TITLE
SenderFunc depends on an unexported type

### ISSUE THREAD

**Issue by meAmidos** [AsynkronIT/protoactor-go#104]
I am trying to use ```WithOutboundMiddleware()``` which requires middleware defined with ```SenderFunc```. The ```SenderFunc``` is currently defined as:

```type SenderFunc func(c Context, target *PID, envelope messageEnvelope)```

That is, to create my custom middleware, I have to use the ```messageEnvelope``` which, unfortunately, is impossible since it's not an exported identifier.

Solution: change the SenderFunc signature or make ```messageEnvelope``` (and, consequently, ```messageHeader```) exported identifiers.

**Comment by rogeralsing** [comment]
Hi, thanks for reporting.
I have exported the identifier now.
The outbound middleware is fresh out of the bakery so please report any problems with it.

Thanks

**Comment by meAmidos** [comment]
Thank you for reacting so promptly. It works now.
