### ISSUE TITLE
Middleware and localContextReceiver

### ISSUE THREAD

**Issue by meAmidos** [AsynkronIT/protoactor-go#105]
Currently, a middleware chain is constructed in such [a way](https://github.com/AsynkronIT/protoactor-go/blob/4f4e1d1ccb8d497180e2ed203852781813b66d26/actor/props.go#L49) that the final element of the chain is the `localContextReceiver` which invokes the actual actor's `Receive()` method. The problem is that localContextReceiver expects the context it gets as an argument to be of the `localContext` type:

```
func localContextReceiver(ctx Context) {
	a := ctx.(*localContext)
	if _, ok := a.message.(*PoisonPill); ok {
		a.self.Stop()
	} else {
		a.receive(ctx)
	}
}
```

So, all the way through the chain the context is propagated as an interface type (`actor.Context`) and only in the end, it is asserted to a specific type. If the `localContextReceiver` could avoid this assertion and pass through the context simply as `actor.Context` interface type, this would make way for a whole new category of middleware which would be able to swap the context to something custom. Now, such swapping works only until the context reaches the point of assertion: `a := ctx.(*localContext)`.

For example, imagine a testing middleware where a custom context object would intercept and register all the calls for later examination in tests.

A brief code research shows that the idea is most likely viable, but would require some refactoring. Would you consider a pull request for this?

Alternatively, is there any other way to achieve the same level of interception in a middleware?

**Comment by rogeralsing** [comment]
Absolutely interested. but please check the different perf benchmarks so any change do not affect perf in a significant way.
cc @stuartcarnie

**Comment by meAmidos** [comment]
So, this issue turned out to be a story with a happy ending. Merging of the PR unblocked the possibility of message interception, and I was able to use this mechanic to build a testing middleware  - exactly as it was planned in the beginning. I hope, this could be helpful for someone as an example of middleware or as a tool for writing tests: https://github.com/meAmidos/gopactor.

**Comment by rogeralsing** [comment]
@meAmidos this looks amazing, I'm going to have to dig deeper into this and see if we can replicate the same features in C#
