### ISSUE TITLE
Sending a response when the sender is nil

### ISSUE THREAD

**Issue by meAmidos** [AsynkronIT/protoactor-go#115]
Consider a request-response flow of messages.

There is a `Respond` method in the Context that sends a response message. If we check how it is implemented, we can see that it simply expects that the addressee is provided via the `Sender` method. However, in fact, it is not guaranteed that the sender address is actually available when we use the `Respond`. Whether it's available or not depends solely on how the initial "request" was sent. If it was sent using the `Request` method, then the respondent can see who is the sender and can use it for respond. If it was sent using the `Tell` method, then the respondent can't see the sender and as a result, it tries to send a message to `nil`. When it does so, the actor crashes.

Now, it can be considered a feature if you prefer your actor to panic and crash when it can't send what has to be sent. And if you want to avoid panic you are forced to always check whether the sender is `nil` or not before using `Respond`. In my opinion, it completely eliminates the usefulness of the `Respond`.

I think that `Respond` should be always safe to use and it should be a responsibility of the sender to choose a proper invocation method - `Request` or `Tell`. This choice should not affect the receiver.

So, I propose a simple change: forward the response to the dead letter channel if the addressee is nil.

I'll submit a pull request.

**Comment by rogeralsing** [comment]
Fixed by #116
