### ISSUE TITLE
lfqueue is LGPL code

### ISSUE THREAD

**Issue by bryanpkc** [AsynkronIT/protoactor-go#117]
The code in internal/queue/lfqueue/ is part of https://github.com/antigloss/go, which is licensed under LGPL v3 and, if my understanding is correct, makes it unsuitable for inclusion in protoactor-go which is licensed under Apache v2. The only use of this code should be changed to use internal/queue/mpsc instead.

**Comment by rogeralsing** [comment]
My understanding is that it isnt an issue:
https://github.com/antigloss/go/blob/master/LICENSE
We only use it as a library, which is explained under " Same license (library)"

**Comment by bryanpkc** [comment]
No, that's incorrect. Protoactor-go doesn't use it only as a library through its intended API. Protoactor-go includes a modified version of it. By the wording in LGPL, that means protoactor-go must also be licensed LGPL.
