### ISSUE TITLE
Question about Instrumentations

### ISSUE THREAD

**Issue by joeblew99** [AsynkronIT/protoactor-go#124]
I am getting stuck in various bugs and think better tooling might help myself and others.

What tools are people using out there ?

I am thinking a dashboard as a CLI or other on all the grain s etc.

A first stab would be something like the golang docker watcher. It's elegant and simple and tells me what all the grains are up to.

Curious if there are thoughts on this. Happy. To start a test harness but looking for feedback first :)

**Comment by rogeralsing** [comment]
We do have injection points where we can hook in e.g. mailbox statistics, or middleware for in and outbound messages.
There is however no dashboards or anything like that available yet.

We did talk early on about making a CLI took to query the state of cluster members

**Comment by joeblew99** [comment]
Thanks. I can now see what direction it's going.

A CLI watcher sounds like a great initial tool.

This is a nice golang CLI tool for real time watching of all your dockers.
https://github.com/bcicen/ctop
It's well done imho and can be adapted for watching actors / grains.

Also I use this alot. It's a GUI interface for debugging golang with delve. It was good concurrency support.
https://github.com/aarzilli/gdlv
It's really impressive and is pure golang.
It could be adapted to be a kick arse tool for seeing and even helping write actors.

Have a look if your curious. Both are very high quality imho, and I am interested in helping to push this area forward but don't want to branch off from what you feel is needed.
