### ISSUE TITLE
add README.md testing documentation

### ISSUE THREAD

**Issue by mcwienczek** [AsynkronIT/protoactor-go#129]
Hi,

I'd like to contribute to the project. After you can accept my proposal I will prepare PR.

Spoiler: this will be my second PR ever.

What I'd like to do:

- I'd like to cleanup a little bit readme as I think installation instructions could be easier and more generic. 
- add simple testing instructions to README.md as well

**Comment by rogeralsing** [comment]
Im all for it, it sounds good :)
