### ISSUE TITLE
How does the server know that the client has broken the connection?

### ISSUE THREAD

**Issue by fananchong** [AsynkronIT/protoactor-go#131]
type tcpServerImplActor struct {
    	    impl *TcpServerImpl
    }
    func (state *tcpServerImplActor) Receive(context actor.Context) {
	    switch msg := context.Message().(type) {
	    case *actor.Started:
		    if context.Self() != state.impl.pid {
			    // here, i know new connection coming
		    }
	    case *actor.Terminated:
		    // but, how here can be call?
	    default: 
		    {
 		    }
	    }
    }

**Comment by rogeralsing** [comment]
What is this supposed to do? `context.Self() != state.impl.pid` 
Self will always be the actors own PID.

In order to get a `Terminated` event, you can do `context.Watch(SomeOtherPID)`
That will make the system send the Terminated event whenever the actor behind  `SomeOtherPID` has died.

**Comment by alex023** [comment]
the follow code  is modified from “examples/chat/server/main.go” ,You can easily find the difference with the [original code ](https://github.com/AsynkronIT/protoactor-go/blob/dev/examples/chat/server/main.go)
```go
package main

import (
	"log"

	"github.com/AsynkronIT/goconsole"
	"github.com/AsynkronIT/protoactor-go/actor"
	"github.com/AsynkronIT/protoactor-go/examples/chat/messages"
	"github.com/AsynkronIT/protoactor-go/remote"
	"github.com/emirpasic/gods/sets/hashset"
)

func notifyAll(clients *hashset.Set, message interface{}) {
	for _, tmp := range clients.Values() {
		client := tmp.(*actor.PID)
		client.Tell(message)
	}
}

func main() {
	remote.Start("127.0.0.1:8080")
	clients := hashset.New()
	props := actor.FromFunc(func(context actor.Context) {
		switch msg := context.Message().(type) {
		case *messages.Connect:
			log.Printf("Client %v connected", msg.Sender)
			clients.Add(msg.Sender)
			msg.Sender.Tell(&messages.Connected{Message: "Welcome!"})
			//add code: to be a watcher for catch *actor.Terminated when client is disconnected
			context.Watch(msg.Sender)
		case *messages.SayRequest:
			notifyAll(clients, &messages.SayResponse{
				UserName: msg.UserName,
				Message:  msg.Message,
			})
		case *messages.NickRequest:
			notifyAll(clients, &messages.NickResponse{
				OldUserName: msg.OldUserName,
				NewUserName: msg.NewUserName,
			})
		//add code: catch *actor.Terminated
		case *actor.Terminated:
			clients.Remove(msg.Who)
		}
	})
	actor.SpawnNamed(props, "chatserver")
	console.ReadLine()
}

```
