### ISSUE TITLE
default size of endpointmanger's write queue is so large, may be this can increase gc time.

### ISSUE THREAD

**Issue by killgxlin** [AsynkronIT/protoactor-go#133]

**Comment by rogeralsing** [comment]
In what sense? the endpoint manager is established once per connection. there is no rapid creation/deactivation of it.

Can you elaborate on this?

**Comment by killgxlin** [comment]
each process has only one endpointmanager, but the endpointmanager has a bounded mailbox who has a ringbuffer. the default size of the ringbuffer is 1000000, and each of its elements has an allocated object. so there are lots of objects inuse. gc time last long.

**Comment by killgxlin** [comment]
try this https://gist.github.com/killgxlin/29b2fbaccc3c29bc83286e2fccb55a40
1 go build && GODEBUG=gctrace=1 ./binname -wqsize=1000000
gc 5 @2.241s 5%: 0.003+0+89 ms clock, 0.026+0/16/18+718 ms cpu, 40->40->40 MB, 40 MB goal, 8 P (forced)                                                                                       
gc 6 @3.057s 7%: 0.005+0+81 ms clock, 0.043+0/16/18+649 ms cpu, 40->40->40 MB, 40 MB goal, 8 P (forced)                                                                                       
gc 7 @3.537s 8%: 0.002+0+84 ms clock, 0.023+0/16/18+677 ms cpu, 40->40->40 MB, 40 MB goal, 8 P (forced)                                                                                       
gc 8 @4.073s 9%: 0.002+0+82 ms clock, 0.021+0/16/18+663 ms cpu, 40->40->40 MB, 40 MB goal, 8 P (forced)                                                                                     
gc 9 @4.313s 10%: 0.003+0+86 ms clock, 0.025+0/16/18+695 ms cpu, 40->40->40 MB, 40 MB goal, 8 P (forced)
2go build && GODEBUG=gctrace=1 ./binname -wqsize=100000
gc 2 @0.642s 2%: 0.003+0+13 ms clock, 0.027+2.6/1.8/0.91+107 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)
gc 3 @1.161s 2%: 0.003+0+13 ms clock, 0.025+2.6/1.8/0.91+105 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)
gc 4 @1.586s 2%: 0.003+0+13 ms clock, 0.028+2.6/1.8/0.91+108 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)
gc 5 @1.953s 2%: 0.002+0+13 ms clock, 0.023+2.6/1.8/0.91+107 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)
gc 6 @2.281s 3%: 0.002+0+13 ms clock, 0.022+2.6/1.8/0.91+107 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)
gc 7 @2.633s 3%: 0.003+0+13 ms clock, 0.024+2.6/1.8/0.91+108 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)
                                                                                                        
gc 8 @2.913s 3%: 0.002+0+13 ms clock, 0.023+2.6/1.8/0.91+108 ms cpu, 5->5->5 MB, 5 MB goal, 8 P (forced)

**Comment by alex023** [comment]
I can not reproduce this phenomenon ,use the same code。
## output
```shell
go build && GODEBUG=gctrace=1 ./[binname]  -wqsize=1000000

gc 1 @0.002s 22%: 0.50+5.9+0.051 ms clock, 1.5+0.22/5.8/0.36+0.15 ms cpu, 8->10->10 MB, 9 MB goal, 4 P
gc 2 @0.010s 20%: 0.004+3.6+0.032 ms clock, 0.016+0.13/3.6/2.7+0.12 ms cpu, 11->12->12 MB, 20 MB goal, 4 P
gc 3 @0.020s 17%: 0.008+10+0.037 ms clock, 0.035+0.18/9.4/2.4+0.14 ms cpu, 17->20->20 MB, 24 MB goal, 4 P
gc 4 @0.049s 15%: 0.011+26+0.043 ms clock, 0.044+0.42/26/0.91+0.17 ms cpu, 31->39->39 MB, 40 MB goal, 4 P
gc 5 @1.972s 1%: 0.012+0+11 ms clock, 0.048+0.42/26/0.91+47 ms cpu, 40->40->40 MB, 40 MB goal, 4 P (forced)
gc 6 @2.995s 1%: 0.002+0+12 ms clock, 0.008+0.42/26/0.91+50 ms cpu, 40->40->40 MB, 40 MB goal, 4 P (forced)
gc 7 @4.932s 1%: 0.001+0+11 ms clock, 0.007+0.42/26/0.91+44 ms cpu, 40->40->40 MB, 40 MB goal, 4 P (forced)
gc 8 @6.019s 1%: 0.001+0+11 ms clock, 0.007+0.42/26/0.91+46 ms cpu, 40->40->40 MB, 40 MB goal, 4 P (forced)
gc 9 @6.875s 1%: 0.001+0+11 ms clock, 0.006+0.42/26/0.91+44 ms cpu, 40->40->40 MB, 40 MB goal, 4 P (forced)
gc 10 @7.299s 1%: 0.001+0+12 ms clock, 0.006+0.42/26/0.91+48 ms cpu, 40->40->40 MB, 40 MB goal, 4 P (forced)
```
## env
- golang: 1.8.3
- macos: 10.12.5 (16F73)
- cpu: 3.3 GHz Intel Core i5

**Comment by killgxlin** [comment]
my previous env is:
golang: 1.7.5
macos: 10.12.3
cpu: 2.2 GHz Intel Core i7

and i upgrade to golang 1.8.3
the gc time reduce to about 10 ms.

i search about "golang 1.8 gc"
got this "
Garbage Collector
Garbage collection pauses should be significantly shorter than they were in Go 1.7, usually under 100 microseconds and often as low as 10 microseconds. See the document on eliminating stop-the-world stack re-scanning for details. More work remains for Go 1.9.
"

so this is not a problem above 1.8, but even a little slow below 1.7
