### ISSUE TITLE
context.message will be modified after the Receive function returns, so the message in this closure may be invalid

### ISSUE THREAD

**Issue by killgxlin** [AsynkronIT/protoactor-go#135]
https://github.com/AsynkronIT/protoactor-go/blob/dev/cluster/pid_cache.go#L65-L81

**Comment by rogeralsing** [comment]
`ctx.AwaitFuture` captures the current message and runs the continuation with the message/context reset to the state it was in (it sends the continuation and current message as a message to itself)

Have you observed any case where this does not work as expected?

**Comment by killgxlin** [comment]
so sorry, my fork is not new. and i don't follow deeper. this bug is fixed at this line.
https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/local_context.go#L447

**Comment by killgxlin** [comment]
this is a bug already fixed, so close this issue.
