### ISSUE TITLE
Using Proto.Actor in production

### ISSUE THREAD

**Issue by mvbaffa** [AsynkronIT/protoactor-go#16]
Hi,

I am planning to migrate a Scala Realtime Transaction Tracking to Go using Gam. I need a faster and more concise application.

I am using Gam and it is working perfectly, Is Gam ready for production ? 

Thanks

**Comment by rogeralsing** [comment]
To give you the completely honest view.
I havent used this in production myself, so I would imagine there are a few quirks still in here.
There are some missing features, but no known bugs right now.

There have been a lot of attention around the lib, soon 700 stars here, not that this is a good quality measurement, but at least there have been quite a few eyes on the code.

I will ofc do my best to fix any problems if they arise.

**Comment by rogeralsing** [comment]
There is a major product going into production in the near future if things plays out as expected.
cc @stuartcarnie for more details

**Comment by mvbaffa** [comment]
Thanks I will check it out

Em 07/01/2017 15:39, "Roger Johansson" <notifications@github.com> escreveu:

**Comment by germanvazquez-rfk** [comment]
Hey, I now this is closed but need to ask :)
We are planning in my company to use GAM in prod. 
Is there any news or progress on this?

**Comment by germanvazquez-rfk** [comment]
Hey, I know this is closed but need to ask :)
We are planning in my company to use GAM in prod. 
Is there any news or progress on this?
