### ISSUE TITLE
In cluster, grains with different type but the same name will generate the same PID

### ISSUE THREAD

**Issue by killgxlin** [AsynkronIT/protoactor-go#165]
The PID pattern is "IP:PORT/Remote$NAME" which do not contain type, could it contain type? Like this "IP:PORT/Remote$TYPE/NAME"
@rogeralsing

**Comment by PotterDai** [comment]
This will result in different Type name between go/c#/others I guess?

**Comment by otherview** [comment]
I've been prepending the type with a dash. No issues so far.

```
protoGen.GetGrainA("TypeA-" + grainID)
```
