### ISSUE TITLE
Interoperating between c# and .net

### ISSUE THREAD

**Issue by gedw99** [AsynkronIT/protoactor-go#167]

**Comment by gedw99** [comment]
Wondering if this works yet ?

I want to use this on servers , desktop and mobile.

Am asking because it seems the two projects are in a state of flux and thought it was worth just asking first

**Comment by rogeralsing** [comment]
Using Proto.Remote works fine. for Cluster support, there is a PR right now to fix this

**Comment by gedw99** [comment]
thanks roger.
Proto.Remote is just what i need. Will give it a whirl.

Heres my plan:
- I am planning to run the server and client services in golang. The Client Services is literally a service that runs on the clients (ios, android, desktops).
The GUI (ios, android, desktop) will run in Xamarin. Its quite capable these days - finally.
The GUi and Client Services can then run a Remote Session over HTTP (forgoet IPC for now :))
The Client Services and Server can use a CRDT like sync protcol.

I have crdt sync working between JS apps, but not yet as a CRDT / Evetn store type pattern between the Client Service and the Server yet.

If you have any thought feel free to holler. 
I wil try to send info and repo URL of my progres if you want.

**Comment by rogeralsing** [comment]
If you do any CRDT related work for Proto.Actor that woduld be highly interesting for a lot of people :-)

**Comment by gedw99** [comment]
Will see how the port from js to golang & c# goes. Will take a while.

What I am struggling with is an architectural pattern to use actors with event sourcing / crdt. It would be a powerful mix and I need an event queue for crdt pattern to work.
I know this is a bit vague but I am hoping you see what I am getting at.

It may be that you are using an event queue for the cluster in order to provide HA properties ?

**Comment by PotterDai** [comment]
Should be working now.
