### ISSUE TITLE
Lack of documentation for persistence providers

### ISSUE THREAD

**Issue by LizBode** [AsynkronIT/protoactor-go#170]
Hi, I am currently working on developing a PostgreSQL persistence provider. I am having issues with the development due to the lack of documentation regarding the persistence provider and the examples that are provided. I am particularly struggling with knowing how to call the persistence provider that I have created in order to see if it is restoring the state properly. Could you please provide a more diverse example of a persistence provider with comments instead of just the InMemoryProvider?
Please let me know if there is any additional information that you require in order to assist me with this issue.

**Comment by tomliversidge** [comment]
I don't know if it helps or not but there are more examples of the persistence provider in the .net code and docs - maybe take a look at how it is used there?

**Comment by LizBode** [comment]
Hi, I have had a look at those examples but I was still struggling due to the differences in coding style and language. However, I did see that there are more examples on the master branch, so I'm in the process of working through those. I'm going to leave the issue open for support, if thats ok, if I am able to complete the provider then I will close the issue. Thank you for the response!
