### ISSUE TITLE
Add AdvertisedHost and AdvertisedPort

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#184]
In .NET we have this:
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/RemoteConfig.cs#L45

This means that you can advertise one address to the outside world, while still binding to a local address/port.

This will be helpful for any form of cloud or container environment

**Comment by gosthell** [comment]
I need this, my actors run inside containers and cannot respond to each others. Can you provide any clue about where I could start looking to implement it ?

**Comment by rogeralsing** [comment]
Closed by 328
