### ISSUE TITLE
Expose actor.Context to the code gen grains

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#185]
Currently, it is not possible to spawn child actors using the code generated grains.
They are simple RPC interfaces.

It would be nice to be able to at least get access to a narrower context with the Spawn* methods on so that grains can have child hierarchies

**Comment by PotterDai** [comment]
You got it fixed here https://github.com/AsynkronIT/protoactor-go/pull/189.  = )
