### ISSUE TITLE
Can join the featrue that the eventstream payload on Kafka?

### ISSUE THREAD

**Issue by leenux** [AsynkronIT/protoactor-go#188]
If protoactor-go can integrate Kafka together,event should need not care who pub and who sub in coding.

**Comment by cupen** [comment]
Er ... pub-sub with Kafka is a good idea, but `protoactor` is just a actor framework. It only need to does something what actor framework needs. 
Any way, we can using `protoactor` with Kafka for pub-sub, by our hands, as what we want.

**Comment by leenux** [comment]
Now we can implement the persistence of the actor on Dapr, and support the binding of Kafka, but Dapr is still not available for production
