### ISSUE TITLE
emptyMessageHeader should not be a Global Var

### ISSUE THREAD

**Issue by feyman2016** [AsynkronIT/protoactor-go#196]
Hi,I'm working on tracing with zipkins and I found that emptyMessageHeader  is currently a global var, and it is used by `context.Tell` , `pid.Tell` , `Request` and `RequestFuture` methods, when I modify and propagate the global variable `MessageHeader` between actors, you can imagine it would mess up.

For now, If I change the 
```
func (ctx *localContext) Tell(pid *PID, message interface{}) {
	ctx.sendUserMessage(pid, message)
}

func (ctx *localContext) sendUserMessage(pid *PID, message interface{}) {
	if ctx.outboundMiddleware != nil {
		if env, ok := message.(*MessageEnvelope); ok {
			ctx.outboundMiddleware(ctx, pid, env)
		} else {
			ctx.outboundMiddleware(ctx, pid, &MessageEnvelope{
				Header:  emptyMessageHeader,
				Message: message,
				Sender:  nil,
			})
		}
	} else {
		pid.ref().SendUserMessage(pid, message)
	}
}
```

to

```
func (ctx *localContext) Tell(pid *PID, message interface{}) {
	ctx.sendUserMessage(pid, message)
}

func (ctx *localContext) sendUserMessage(pid *PID, message interface{}) {
	if ctx.outboundMiddleware != nil {
		if env, ok := message.(*MessageEnvelope); ok {
			ctx.outboundMiddleware(ctx, pid, env)
		} else {
			ctx.outboundMiddleware(ctx, pid, &MessageEnvelope{
				Header:  make(messageHeader),
				Message: message,
				Sender:  nil,
			})
		}
	} else {
		pid.ref().SendUserMessage(pid, message)
	}
}
```
it worked. I didn't test `Request` and `RequestFuture`, but I think the situation should be the same.
What do you think of this?@rogeralsing

**Comment by alex023** [comment]
At present, the method provided by the context only Tell, Request is not enough to meet the environment variable delivery. 
See also #200

**Comment by alex023** [comment]
Sometimes, the default global variable is necessary, but the variable name `emptyMessageHeader`will be troubling.
In addition, the method provided by context only `Tell`,` Request` is not enough to meet the transfer of private environment variables, see #200

**Comment by bryanpkc** [comment]
The use of global variables like `emptyMessageHeader` reduces memory pressure. In our applications, the cost of memory allocation and garbage collection for messages (as much as tens of thousands per second) is very large. An optional feature like tracing should not force the creation of unique headers in all cases. Just my two cents.

**Comment by alex023** [comment]
We should use the PID, instead of using the Context method, if concerned about the performance. The focus of Context news head, there are outbox_middle implementation. The same name of the Context method provides plug-ins and environment variables are its value, if the scene of global information applications are very much, the frame should increase the options for trans private information

**Comment by PotterDai** [comment]
I think the better way could be expose messageHeader constructor with
`func NewEmptyMessageHeader() *messageHeader`
and in outbound middleware just use
`envelope.Header = actor.NewEmptyMessageHeader()`
if new header is necessary to be created.

**Comment by feyman2016** [comment]
I was initially thought the same as you, but considering to reduce memory pressure, using the `emptyMessageHeader` might be a compromising choice, actually, in context.Tell and context.Request , I solved the MessageHeader problem by creating an MessageHeader instance in the middleware. @PotterDai

**Comment by feyman2016** [comment]
Are you also working on tracing in protoActor? @alex023 For now , I think using `context.Tell & Request` for tracing is fine, because middleware can be used to handle the MessageHeader. But `pid.Tell & Request`  does not have such mechanism.

**Comment by feyman2016** [comment]
@bryanpkc  I accept your opinion and as I mentioned above, `context.Tell & Request` can just work fine  but the pid.Tell & Request still faces the problem.For ex.

```
func (pid *PID) Request(message interface{}, respondTo *PID) {
	env := &MessageEnvelope{
		Message: message,
		Header:  emptyMessageHeader,
		Sender:  respondTo,
	}
	pid.ref().SendUserMessage(pid, env)
}
```

pid.Request is widely used in the `Router-routee` mechanism and obviously the original `MessageHeader` is dropped and an `emptyMessageHeader` comes as an substitution when the msg flows through the router.  So , this is a little  annoying and seems can not be solved by the caller. 
@rogeralsing  What do you think of this?

```
in router/process.go:

func (ref *process) SendUserMessage(pid *actor.PID, message interface{}) {
	msg, sender := actor.UnwrapEnvelope(message)
	if _, ok := msg.(ManagementMessage); !ok {
		ref.state.RouteMessage(msg, sender)
	} else {
		r, _ := actor.ProcessRegistry.Get(ref.router)
		// Always send the original message to the router actor,
		// since if the message is enveloped, the sender need to get a response.
		r.SendUserMessage(pid, message)
	}
}

in router/roundrobin_router.go

func (state *roundRobinState) RouteMessage(message interface{}, sender *actor.PID) {
	pid := roundRobinRoutee(&state.index, state.values)
	pid.Request(message, sender)
}

```

**Comment by alex023** [comment]
@feyman2016
 i try zipkin about a mouth ago, and i give up now. because:
1. in one node, ctx can not transfer envelope.if you want send msg from actor.A to actor.C cross actor.B ,just like A--->B--->C--->A(note C respond here). We need new method `ctx.Forward`. just context.Tell and context.Request is not satisfy with business, see #200.
2. In multi node, Envelop.Header will discard. There are not Header definition in package remote(struct is `MessageBatch` and  `MessageEnvelope`).

I really wish my current understanding was wrong！

**Comment by feyman2016** [comment]
@alex023   
1. If you want to implement spanContext propagation in the situation you mentioned above, you can implement a outboundmiddleware , when sending msgs by context.* , you can intercept them in the outboundmiddleware  and get messageHeader of the msg that is currently processing, and put it in the envelop .
2. I didn't try remote or cluster scenario for now ~~

**Comment by PotterDai** [comment]
@feyman2016  This pr should fix the cluster/remote problem, as well as router.
https://github.com/AsynkronIT/protoactor-go/pull/206
Still, in Pid.Tell/Request, header will still be nil, but context.Tell/Request should be good enough in majority of time I think.

**Comment by feyman2016** [comment]
@PotterDai 
Thanks, I have reviewed the pr #206 , which is fine .And using `context.Tell` in the router is more concise in router because sender is already implicitly included in the message.
And for now , context.Tell and Request is enough .

**Comment by PotterDai** [comment]
Fixed here https://github.com/AsynkronIT/protoactor-go/pull/206
