### ISSUE TITLE
method "Forward" should be provided in actor.Context

### ISSUE THREAD

**Issue by alex023** [AsynkronIT/protoactor-go#200]
## Question
 In the actual business, we face the message there will be several situations:
1. Do not need reply:  
  pipe: actor.A--->actor.B---->actor.C
  We can use `ctx.Tell`
2. Do need reply:      actor.A---->actor.B--->actor.A
We can use `ctx.Request`
3. Do need reply by last actor:
actor.A---->actor.B---->actor.C---->actor.A
if we want transfer env by envelop.header ，what should actor.B adapt method?

## Suggest
I think ctx.Forward is necessary
the code may be:
```go
//context.go
type Context interface{
       //...
       //Forward sends a message to the given PID and also provides message orginal Sender PID
	Forward(pid *PID ,message interface{})
       //...
}
```
```go
//local_context.go
//Forward sends a message to the given PID and also provides message orginal Sender PID
func (ctx *localContext) Forward(pid *PID, message interface{}) {
	env := &MessageEnvelope{
		Header:  ctx.messageHeader(),
		Message: message,
		Sender:  ctx.Sender(),
	}
	ctx.sendUserMessage(pid, env)
}

func (ctx *localContext) messageHeader() messageHeader {
	envelope, ok := ctx.message.(*MessageEnvelope)
	if ok {
		return envelope.Header
	}
	return emptyMessageHeader
}
```
Looking forward to a better way！

**Comment by rogeralsing** [comment]
Closed by #203
