### ISSUE TITLE
The Tell, Request, RequestFuture in actor.Context should be able to pass private envelop.Header

### ISSUE THREAD

**Issue by alex023** [AsynkronIT/protoactor-go#202]
## Description
Currently, there is a `Tell`, `Request`,`RequestFuture` method for both **PID** and **Context**, but the latter is able to use Outbox_Middleware. Once we need to pass the message environment variables, we need to have multiple assignments in the middleware implementation. Different Header, Middleware must be different.
I noticed that the `Tell`, `Request`,`RequestFuture` method assign envelop.Header to the global emptyHeader in  **local_context**. If the client application request with header information for debug(just seq or more), this time is difficult to meet. 
Why not pass the head message of the current message by default?

## Suggest
I think it is necessary to pass current header if it is not nil. If we can, we do not need to specify a different middle implementation for each actor Props.
the code like this:
```
//get current header ,otherwise return emptyMessageHeader
func (ctx *localContext) currentHeaderOrDefault() messageHeader {
	envelope, ok := ctx.message.(*MessageEnvelope)
	if ok {
		return envelope.Header
	}
	return emptyMessageHeader
}

func (ctx *localContext) Request(pid *PID, message interface{}) {
	env := &MessageEnvelope{
		Header:  ctx.currentHeaderOrDefault(), //<----change this
		Message: message,
		Sender:  ctx.Self(),
	}
	ctx.sendUserMessage(pid, env)
}

func (ctx *localContext) RequestFuture(pid *PID, message interface{}, timeout time.Duration) *Future {
	future := NewFuture(timeout)
	env := &MessageEnvelope{
		Header:  ctx.currentHeaderOrDefault(),  //<----change this
		Message: message,
		Sender:  future.PID(),
	}
	ctx.sendUserMessage(pid, env)

	return future
}

func (ctx *localContext) sendUserMessage(pid *PID, message interface{}) {
	if ctx.outboundMiddleware != nil {
		if env, ok := message.(*MessageEnvelope); ok {
			ctx.outboundMiddleware(ctx, pid, env)
		} else {
			ctx.outboundMiddleware(ctx, pid, &MessageEnvelope{
				Header:  ctx.currentHeaderOrDefault(),  //<----change this
				Message: message,
				Sender:  nil,
			})
		}
	} else {
		pid.ref().SendUserMessage(pid, message)
	}
}
```
Hope everyone can discuss this issue！

**Comment by PotterDai** [comment]
Fixed here https://github.com/AsynkronIT/protoactor-go/pull/206
