### ISSUE TITLE
the actor instance is still reuse even after panic restarting

### ISSUE THREAD

**Issue by alex023** [AsynkronIT/protoactor-go#212]
when actor panic, the instance is reused? This is different from akka .

- protoActor:clean chidren actor, except variable of instance
- AKKA: all reset

I found reason from *props.go*:
```go
func makeProducerFromInstance(a Actor) Producer {
	return func() Actor {
		return a
	}
}
```
is it problem?

### go for protoactor:
```go
package main

import (
	"fmt"
	"time"
	"github.com/AsynkronIT/protoactor-go/actor"
	"reflect"
)

type parentActor struct {
	count int  //if panic it will not reset
}

func (pa *parentActor) Receive(context actor.Context) {
	pa.count++
	msgType := reflect.TypeOf(context.Message())
	fmt.Printf("%v: receive message[%v] \n", pa.count,msgType)

	switch msg := context.Message().(type) {
	case *actor.Started:
		fmt.Println("   Started, initialize actor here")
	case *actor.Stopping:
		fmt.Println("   Stopping, actor is about shut down")
	case *actor.Stopped:
		fmt.Println("   Stopped, actor and it's children are stopped")
	case *actor.Restarting:
		fmt.Println("   Restarting, actor is about restart")
	case MessageInit:
		fmt.Println("   receive MessageInit")
		context.Spawn(actor.FromInstance(&childActor{}))
	case MessageCaculate:
		for _, child := range context.Children() {
			child.Request(msg, context.Sender())
		}
	case MessagePanic:
		fmt.Println("   receive MessagePanic")
		panic("receive MessagePanic")
	}
}

type childActor struct{}

func (ca *childActor) Receive(context actor.Context) {
	switch msg := context.Message().(type) {
	case MessageCaculate:
		fmt.Printf("   childActor caculate:%v multi %v =%v \n", msg.x, msg.y, msg.x*msg.y)
	}
}

type MessageInit struct{}
type MessagePanic struct{}
type MessageCaculate struct {
	x int
	y int
}

func main() {
	props := actor.FromInstance(&parentActor{})
	actor := actor.Spawn(props)

	actor.Tell(MessageInit{})
	time.Sleep(1 * time.Second)

	actor.Tell(MessageCaculate{2, 7})
	time.Sleep(1 * time.Second)

	actor.Tell(MessagePanic{})
	time.Sleep(1 * time.Second)

	actor.Tell(MessageCaculate{8, 2})
	time.Sleep(1 * time.Second)

	fmt.Println("read sent send stop")
	actor.Stop()

	//console.ReadLine()
}
```

### scala for akka
```scala
import java.util.concurrent.TimeUnit
import akka.actor.{Actor, ActorSystem, Props}

case class MessageCaculate(x: Int, y: Int)

case object MessageInit

case object MessagePanic

class ChildChild extends Actor {
  override def receive: Receive = {
    case MessageCaculate(x, y) =>
      println(s"   childActor caculate:$x multi $y =${x * y}")

  }
}

class ParentActor extends Actor {
  private var counter: Int = _ //it will reset if actor panic

  def getCounter: Int = {
    counter += 1
    counter
  }

  override def receive: Receive = {
    case MessageInit =>
      context.actorOf(Props(new ChildChild()), "child")
    case msg: MessageCaculate =>
      context.child("child") match {
        case Some(e) => e ! msg
        case None =>
          println("haven't child")
      }
    case MessagePanic =>
      7 / 0
  }

  override def postStop(): Unit = {
    println(getCounter + "  actorTester stoped!")
  }

  override def preStart(): Unit = {
    println(getCounter + "  actorTester preStart!")
  }

  override def postRestart(reason: Throwable): Unit = {
    println(getCounter + "  actorTester postRestart!")
  }
}

object Test extends App {
  val system = ActorSystem("tester")
  val tester = system.actorOf(Props[ParentActor])

  tester ! MessageInit
  TimeUnit.SECONDS.sleep(1)

  tester ! MessageCaculate(2, 7)
  TimeUnit.SECONDS.sleep(1)

  tester ! MessagePanic
  TimeUnit.SECONDS.sleep(1)

  tester ! MessageCaculate(8, 2)
  TimeUnit.SECONDS.sleep(2)

  system.terminate()
}
```

**Comment by rogeralsing** [comment]
The issue in this case is `FromInstance`, Try `FromProducer` which gives the behavior you want.

`FromInstance` was an early convenience method from the very early days of Proto.Actor (or GAM at the time)
As it uses an instance, there is no decent way to "reset" it, reset it to what? completely empty state, or default state for that specific type?

Similar behavior could be seen for `FromFunc` if you close over non local state state.

cc @PotterDai should we deprecate FromInstance? it fills no good purpose other than a few keystrokes compared to FromProducer

**Comment by PotterDai** [comment]
@rogeralsing Yep, agree! =) I think this function is misleading, and we also don't have this in DotNet version.

**Comment by bryanpkc** [comment]
`FromInstance` is confusing to new beginners, especially those who come from languages where everything is an object, but it can be useful for producing actors with immutable state (a.k.a. value-type actors). Also, its convenience cannot be underestimated. `actor.FromInstance(&Fish{count: 42})` is much nicer than:
```go
actor.FromProducer(func() actor.Actor {
	return &Fish{count: 42}
})
```
This is especially true for actor types that are primitives or plain structs.

To get the behavior that @alex023 expects, we could use reflection. I have a prototype in my fork:

https://github.com/Huawei-PTLab/protoactor-go/commit/b364259

This only handles pointers now, but the idea can be extended to other reference types (slices, maps, etc.)

**Comment by PotterDai** [comment]
@bryanpkc Agree! However I think the issue here is not about confusing new beginners coming from other languages, but that we do have a method that is not fully functional.
It will definitely help if you could make a pull request with the fix in your linked fork =)

**Comment by alex023** [comment]
Thanks all. 
as @PotterDai  said, the `actor.FromInstance`  should not be open until it got fixed.
Now, it's a wise choice for me to use `actor.FromFromProducer` to solve business problems.

**Comment by bryanpkc** [comment]
After some thought, I decided to leave `FromInstance` alone and added a new function called `FromTemplate` to do what I proposed. I think providing godoc for `FromInstance` to document its intention/limitation is sufficient. An optional to-do could be to rename it to `FromValue` and deprecate the original name `FromInstance`, but I am fine with not renaming it.
