### ISSUE TITLE
Crdt / Alka and convergent computation

### ISSUE THREAD

**Issue by gedw99** [AsynkronIT/protoactor-go#221]
There is a akka lib for using crdt for distributed computation.

https://doc.akka.io/docs/akka/snapshot/distributed-data.html?language=scala

Does this exist yet in this lib ?
There are some create crdt libs out there and maybe it makes sense to add this ?
I am using y.js currently. It's able to converge all it's data types and very easy to use compared to other crdt libs

**Comment by PotterDai** [comment]
@gedw99 Nope, I don't think there is one. If you would like to contribute, that will be very appreciated = )

**Comment by rogeralsing** [comment]
While I personally find CRDT's very fascinating, this could be a huge undertaking, especially if we intend to make it multi platform.

Which would be cool, my own time is somewhat limited right now, but if there is large enough community pushing for it, I'm all ears

**Comment by gedw99** [comment]
Here is some updates on some libraries worth looking at if it helps.
Curious what you and others think.

ron
https://github.com/gritzko/ron
- its very complicated  and i have not had time to dig into getting a test harness up for it

roshi
https://github.com/soundcloud/roshi
- Another take on it. This basically allows the WAL ( Write ahead log) tha i assume holds Operations ( OT's). Its a different architectural approach to solving the same issue.
Roshi was used to make sound cloud scale.

y.js
https://github.com/y-js/yjs
this is much more avances but is written is JS. I spoke with the developer about a golang version and so then it can be cross compiled to WASM ( which is not possible with golang wip branch).

---

I can imagine that Roshi has a good applicability to protoactor-go. Its basically allows you to partition your cluster and have it reconcile the WAL when they rejoin.
Also of course useful for client side stuff also.
It also fits nicely with the command pattern when you put the command operation names and data onto the WAL and feed into your system.

**Comment by rogeralsing** [comment]
Marking as out of scope.
I'd love to see someone picking upp the ball here, but from the core bits, it's just too much for us to handle atm.
