### ISSUE TITLE
sync.Map undefined

### ISSUE THREAD

**Issue by cloudfreexiao** [AsynkronIT/protoactor-go#222]
hi 
my project go version is 1.85 
compiler protoactor errror sync.Map undefined is really a bug???  thanks
https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/guardian.go#L11

**Comment by PotterDai** [comment]
sync.Map was introduced since golang 1.9 (https://medium.com/@deckarep/the-new-kid-in-town-gos-sync-map-de24a6bf7c2c)
@rogeralsing  Hmmm, not sure how to deal with different versions in Go.

**Comment by cloudfreexiao** [comment]
thanks 
I upgrade go version
