### ISSUE TITLE
Cross compilation protoactor-go ?

### ISSUE THREAD

**Issue by ealoshinsky** [AsynkronIT/protoactor-go#227]
And so on your laptop with the Linux operating system for copying we execute the following command in the terminal:

> CGO_ENABLED = 0 GOOS = windows GOARCH = 386 go build -o test.exe main.go

Excellent assembly is finished, drag test.exe to the machine with Windows ... Trying to run the test.exe we get the runtime error, the output of the error is shown below:

> D:\public>test.exe
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x4012dc]
> 
> goroutine 1 [running]:
> sync/atomic.AddUint64(0x11820424, 0x1, 0x0, 0x0, 0x1)
>         /usr/lib/go-1.9/src/sync/atomic/asm_386.s:112 +0xc
> github.com/AsynkronIT/protoactor-go/internal/queue/goring.(*Queue).Push(0x118204
> 20, 0x505200, 0x117d0258)
>         /opt/go/src/github.com/AsynkronIT/protoactor-go/internal/queue/goring/qu
> eue.go:57 +0x24f
> github.com/AsynkronIT/protoactor-go/mailbox.(*unboundedMailboxQueue).Push(0x117d
> 0238, 0x505200, 0x117d0258)
>         /opt/go/src/github.com/AsynkronIT/protoactor-go/mailbox/unbounded.go:13
> +0x33
> github.com/AsynkronIT/protoactor-go/mailbox.(*defaultMailbox).PostUserMessage(0x
> 117f2080, 0x505200, 0x117d0258)
>         /opt/go/src/github.com/AsynkronIT/protoactor-go/mailbox/mailbox.go:56 +0
> x87
> github.com/AsynkronIT/protoactor-go/actor.(*localProcess).SendUserMessage(0x117d
> 8140, 0x11820400, 0x505200, 0x117d0258)
>         /opt/go/src/github.com/AsynkronIT/protoactor-go/actor/local_process.go:1
> 5 +0x36
> github.com/AsynkronIT/protoactor-go/actor.(*PID).Tell(0x11820400, 0x505200, 0x11
> 7d0258)
>         /opt/go/src/github.com/AsynkronIT/protoactor-go/actor/pid.go:45 +0x49
> main.main()
>         /tmp/attempt_actor.go:23 +0x96
> 
> D:\public`

What am I doing wrong?  Who can help in the assembly for different platforms?

P.S.  go version go1.9.2 linux/amd64

**Comment by PotterDai** [comment]
@ealoshinsky This is a known bug from Go mentioned here:
https://golang.org/pkg/sync/atomic/#pkg-note-BUG
And should be fixed in this PR.
https://github.com/AsynkronIT/protoactor-go/pull/228

Could you try again?
Thx!

**Comment by ealoshinsky** [comment]
Fixed.

Thx!
