### ISSUE TITLE
Design / API Changes upcoming

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#239]
We have been doing some major API re-work on the .NET side of things.
https://github.com/AsynkronIT/protoactor-dotnet/issues/404

This will cause some breaking changes once implemented for Go.
But it is for the greater good, consistent API, better testability and observability.

**Comment by linkerlin** [comment]
What's going on?
It has a plan?

**Comment by cpx86** [comment]
@linkerlin The mentioned issue specifies the changes we're doing. Mainly it is 1) removing PID.Tell/Request in favor of the newly introduced RootContext (to allow for better middleware support) and 2) renaming of some core concepts, e.g. Tell-> Send, LocalProcess->ActorProcess, LocalContext->ActorContext

From a user's POV it shouldn't be too bloody, we're mainly restructuring the API surface a bit. It is breaking though, hence the heads-up 😅

**Comment by nikoszoisse** [comment]
Any news? Any progress?

**Comment by zxc122333** [comment]
Any update?
