### ISSUE TITLE
How to retrieve a local actor based on spawned name? #question

### ISSUE THREAD

**Issue by nikoszoisse** [AsynkronIT/protoactor-go#258]
Hey guys I have this following concept. How can i retrieve the PID based on spawned name (i ve checked that ProccessRegistry..LocalPIDS returns process but cant do the job)? 
![screenshot 2018-11-15_18-28-56-637](https://user-images.githubusercontent.com/10202115/48566821-647f3780-e904-11e8-9924-22e8fe7712d3.png)
#question

**Comment by PotterDai** [comment]
I think you can get it by calling actor.ProcessRegistry.GetLocal(...name...)

**Comment by nikoszoisse** [comment]
I used that but it doesn't work. Have you tried something similar?

**Comment by PotterDai** [comment]
Oh, my bad. Actually if you just want the pid, you can simply create one by giving your name and your address
`
&actor.PID{Address, Name}
`
since PID is just something like url.

**Comment by nikoszoisse** [comment]
Well, I receive a Deadletter now.. pff so, what is supposed to do? for e.x if I create a actor  "MathewActor", I should be able to retrieve him using actor.ProcessRegistry.GetLocal("MathewActor")?

**Comment by PotterDai** [comment]
Yep, that's right, but typically you should not do that, using &actor.PID{Address, Name} is a better way to solve this.
If it returns DeadLetter, it means the actor is not spawned or is dead.
Did you spawn the actor?

**Comment by nikoszoisse** [comment]
Well, I Did spawned the router actor. Here is how I solved it, but i dont think is a proper way.

`				proc, _ := actor.ProcessRegistry.GetLocal("$1/myRouter")`
					`pid := &actor.PID{
						Address: "nohost",
						Id:      "$1/myRouter",
					}`
			     `proc.SendUserMessage(pid, &DeriveMessage{Who: id.(string)})`

@PotterDai  I believe that it would be better to add a new method ProcessRegistry.GetLocalActor which returns a PID.

**Comment by PotterDai** [comment]
@nikoszoisse 
Hmmm.... this doesn't make sense that it works by this way
What happened if you use this:
```
pid := actor.NewLocalPID("$1/myRouter")
pid.Tell(&DeriveMessage{Who: id.(string)})
```

**Comment by PotterDai** [comment]
@nikoszoisse 
I think I got what's wrong!
The default local address is "nonhost" instead of "nohost".
You can also use actor.NewLocalPID(....name..) to avoid the confusion.

**Comment by nikoszoisse** [comment]
Just tried what you said, That's correct!!! Thank you for your time!!

On 15 November 2018, at 22:09, Potter Dai <notifications@github.com> wrote:

@nikoszoisse
The reason of deadletter is not because (p *Process) is not assigned, it will be automatically assigned if you call pid.Tell(...). The reason you got deadletter is because you didn't use the correct local address, which is "nonhost" instead of "nohost".

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AsynkronIT/protoactor-go","title":"AsynkronIT/protoactor-go","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/AsynkronIT/protoactor-go">https://github.com/AsynkronIT/protoactor-go</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PotterDai in #258: @nikoszoisse \r\nThe reason of deadletter is not because (p *Process) is not assigned, it will be automatically assigned if you call pid.Tell(...). The reason you got deadletter is because you didn't use the correct local address, which is \"**nonhost**\" instead of \"**nohost**\"."}],"action":{"name":"View Issue","url":"<a href="https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805">https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805">https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805</a>", "url": "<a href="https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805">https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [AsynkronIT/protoactor-go] How to retrieve a local actor based on spawned name? #question (#258)", "sections": [ { "text": "", "activityTitle": "**Potter Dai**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@PotterDai", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"AsynkronIT/protoactor-go\",\n\"issueId\": 258,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805">https://github.com/AsynkronIT/protoactor-go/issues/258#issuecomment-439173805</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 411124733\n}" } ], "themeColor": "26292E" } ]

**Comment by PotterDai** [comment]
@nikoszoisse 
Haha, that's great! = )
I should have suggested you using `actor.NewLocalPID(...)` before, that will avoid all those local address hassles = )
