### ISSUE TITLE
Router - group: integer divide by zero

### ISSUE THREAD

**Issue by nikoszoisse** [AsynkronIT/protoactor-go#264]
Hello, I received a message `runtime error: integer divide by zero`
When I set up a router like this
```golang
			redisRouter, _ := context.
				SpawnNamed(
					router.NewRoundRobinGroup(),
					"redisRouter")
```
I solved it by not first creating the routees and then add them. 
e.g.
```golang
			var pids []*actor.PID
			for i := 0; i < int(msg.Count); i++ {
				props := actor.FromProducer(NewRedisActor)
				pid, _ := actor.SpawnPrefix(props, "rediscon_")
				pids = append(pids, pid)
			}
			redisRouter, _ := context.
				SpawnNamed(
					router.NewRoundRobinGroup(pids...).WithMiddleware(middleware.Logger),
					"redisRouter")
```
I will try to create a pull request and fix it if none does it until next week.

**Comment by rogeralsing** [comment]
cc @PotterDai was this ever merged or is this still an issue?

**Comment by nikoszoisse** [comment]
This issue it still exists. Although the way of doing such thing is wrong
and they very end.

**Comment by Qiaojiawei** [comment]
the problem is roundRobinRoutee function use index%len(routees) to get an actor in the actor list, in this case len(routees)=0, it panic.
so we should check the length of rooutees and print error log?

**Comment by PotterDai** [comment]
This should have been fixed in this PR:
https://github.com/AsynkronIT/protoactor-go/pull/284
