### ISSUE TITLE
Best way aggregate messages from several actors?

### ISSUE THREAD

**Issue by gubsky90** [AsynkronIT/protoactor-go#270]
Maybe spawn temporary actor for made this logic. Or actor, who'll be wait for several futures?
Please share how best to do?

Maybe something like: `context.AwaitFutures(actor.Future[]{f1, f2}, func(...))`?

**Comment by rogeralsing** [comment]
If you know the actors that should send the responses. you could spawn up an actor and tell it to wait for x messages. 
e.g. the actor has a counter, say 10. and for each response that comes in, it decrements that counter and stores the message in e.g. a list. when the counter hits 0, you know you have all the responses and can calculate the aggregation based the messages you received.

**Comment by gubsky90** [comment]
Thank you very much)

**Comment by rogeralsing** [comment]
You could also let the aggregator actor keep a dictionary with the PID's of the actors to aggregate as the dict key.

That way, you can ensure you only get one message per actor, the counter version is sensitive if one actor sends multiple messages.
