### ISSUE TITLE
Would poisoning an Actor in GAM be bad ?

### ISSUE THREAD

**Issue by otherview** [AsynkronIT/protoactor-go#288]
From what I'm reading this isn't the *best* behaviour, but might be a minor evil.

- Let's say we want to free some memory.
- After 20 minutes we deem this actor in GAM no longer necessary
- ReceiveTimeout would poison the actor and release it from memory
```
switch msg := ctx.Message().(type) {
case *actor.Started:
		a.inner = x{{ $service.Name }}Factory()
		id := ctx.Self().Id
		a.inner.Init(id[7:]) // skip "remote$"
		ctx.SetReceiveTimeout(20 * time.Minute)
	case *actor.ReceiveTimeout:
		ctx.Self().Poison()
```

This would mean that the silo that holds the grain would still have its reference cached - And would initialize it when requested.. Without issues ? Or am I missing something here ? (Pretty sure I am :) )

Thoughts ?

**Comment by PotterDai** [comment]
@otherview Hi, thank you for asking! = )
the difference between Stop() and Poison() is:
`Stop()` will stop the actor immediately, regardless of unprocessed messages that stacked in the message queue.
`Poison()` will be processed after all the unprocessed messages has been processed, then the actor will stop. In the end they have same effect, only difference is the timing. 

And from my recall, if this is a Cluster system, all actors spawned within the cluster will be watched, which means they will be automatically removed from the system if they got stopped/poisoned. So the reference cache should be removed as well.

**Comment by otherview** [comment]
Good stuff. Thanks @PotterDai !
