### ISSUE TITLE
SupervisionStrategy does not terminate after configured failures

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#3]
The supervisor strategies should terminate the failing actor after enough failures have occurred in the configured timespan.

We need to track PID failures in a map inside the actor cell.

**Comment by goldpasser** [comment]
package main

import (
	"fmt"

	"github.com/rogeralsing/gam/actor"
	"github.com/rogeralsing/goconsole"
)

type Hello struct {
	Who string
}

type AreYouOK struct {
}

type ParentActor struct {
	id      uint64
	started bool
}

func (self *ParentActor) Receive(context actor.Context) {
	switch msg := context.Message().(type) {
	case actor.Started:
		if self.started {
			context.Self().Tell(AreYouOK{})
			return
		}
		self.started = true
		fmt.Printf("parent[%v] starting\n", self.id)
		props := actor.FromProducer(NewChildActor)
		for i := 0; i < 100; i++ {
			child := context.Spawn(props)
			child.Tell(Hello{Who: "Roger"})
		}
	case actor.Stopped:
		fmt.Printf("parent[%v] Stopped\n", self.id)
	case AreYouOK:
		fmt.Printf("parent[%v] recv AreYouOK\n", self.id)
	default:
		fmt.Printf("parent[%v] recv unknown msg, type=[%T]\n", self.id, msg)
	}
}

var gParent = &ParentActor{
	id:      1,
	started: false}

func NewParentActor() actor.Actor {
	return gParent
}

type ChildActor struct {
	id uint64
}

func (self *ChildActor) Receive(context actor.Context) {
	switch msg := context.Message().(type) {
	case actor.Started:
		fmt.Printf("child[%v] starting\n", self.id)
	case actor.Stopping:
		fmt.Printf("child[%v] is about shut down\n", self.id)
	case actor.Stopped:
		fmt.Printf("child[%v] and it's children are stopped\n", self.id)
	case actor.Restarting:
		fmt.Printf("child[%v] is about restart\n", self.id)
	case Hello:
		fmt.Printf("child[%v] recv Hello %v\n", self.id, msg.Who)
		if self.id%2 == 0 {
			//context.Self().Stop()
			panic("panic")
		}
	case AreYouOK:
		fmt.Println("child[%v] recv AreYouOK")
	default:
		fmt.Printf("child[%v] recv unknown msg, type=[%T]\n", self.id, msg)
	}
}

var childId uint64 = 0

func NewChildActor() actor.Actor {
	childId += 1
	return &ChildActor{
		id: childId}
}

func main() {
	decider := func(child *actor.PID, reason interface{}) actor.Directive {
		fmt.Printf("handling failure for child, reason=[%v]\n", reason)
		switch reason.(type) {
		default:
			return actor.StopDirective
		}
	}
	supervisor := actor.NewOneForOneStrategy(10, 1000, decider)
	props := actor.
		FromProducer(NewParentActor).
		WithSupervisor(supervisor)
	actor.Spawn(props)
	console.ReadLine()
}

I modify the supervison example, but it always crash. Am I do something wrong?

**Comment by rogeralsing** [comment]
This has been implemented
