### ISSUE TITLE
Implement One for All supervisor strategy

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#5]
Same as One for One strategy but apply the directive to all children.

**Comment by charignon** [comment]
The easiest solution seems to be adding a `siblings []*PID` argument to the Directive of a SupervisionStrategy but breaks backward compatibility.
Another approach consists of adding a new method to the SupervisionStrategy's interface to be notified of new supervised children, that also breaks backward compatiblity.

How would you suggest building this feature if we want to stay backward compatible?

**Comment by rogeralsing** [comment]
This has been implemented
