### ISSUE TITLE
Complete the sender field of deadletters object.

### ISSUE THREAD

**Issue by killgxlin** [AsynkronIT/protoactor-go#60]
hi bro. i'm thinking about using gam in my project. and i need the sender field of deadletters object.
do you have and plan to add this field? or i can make a pull request myself if you are busy.

**Comment by rogeralsing** [comment]
This should absolutely be added,
If you want, a PR would be welcome
Thanks

**Comment by rogeralsing** [comment]
Waiting for CLA to be signed.

**Comment by rogeralsing** [comment]
Merged
