### ISSUE TITLE
Passivation of Actors and Grains

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#66]
Currently if you spin up a grain, and the grain is idle for a long time, nothing happens.
It would be nice if we could passivate the grain so that it unloads from memory.

There are a few problems that needs to be solved for this:

1. What if there are messages coming into the grain mailbox exactly when the grain is about to passivate?
2. how do we keep this in sync with the owner partition node?

**Comment by rogeralsing** [comment]
Ideas on how to do the actual passivation.

1. The obvious approach is to have something similar to ReceiveTimeout, but didicated for killing idle actors.
this would give a fairly exact time until the actor is passivated.

2. Another approach could be to per actor, keep track of when it's mailbox last ran.
And perform a sweep across the process registry, killing off idle actors.
This would be less exact. but might be cheaper and easier to implement.

Other thoughts?

**Comment by hiyelbaz** [comment]
> What if there are messages coming into the grain mailbox exactly when the grain is about to passivate?

Maybe actor can be recreated where you handle grpc's own timeout exception. (if such a thing exists) 

This thread could be useful at some point: https://github.com/grpc/grpc-go/issues/928

Any idea how Orleans handles this?

**Comment by RussellLuo** [comment]
Per [How Activation-GC Works](https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Activation-Garbage-Collection.html#how-activation-gc-works), Orleans just:

```
periodically scan for activations that have not been used at all for some period of time
```

And the scan is done by [ScanStale()](https://github.com/dotnet/orleans/blob/56dd7842db5436c14e8d046f672bcf75e1c4ace8/src/OrleansRuntime/Catalog/ActivationCollector.cs#L203), which is called in an asynchronous task [CollectActivationsImpl()](https://github.com/dotnet/orleans/blob/c54c7dbe5d941e51e67a9007cb0ffd3b885bc778/src/OrleansRuntime/Catalog/Catalog.cs#L246).

For problem 1 mentioned above:
> 

Orleans handles it in this way:

> You can also instruct the runtime to deactivate the grain next time it becomes idle, by using:
> 
>     protected void DeactivateOnIdle()
>
> An activation is considered idle if it is not processing any message at the moment. If you call DeactivateOnIdle while a grain is processing a message, it will get deactivated as soon as processing of the current message is finished. **If there are any requests queued for the grain, they will be forwarded to the next activation**.
