### ISSUE TITLE
contextualizing Tell

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#69]
In order to fully support passing contextual information the current `PID.Tell` model will not work.
One suggestion is to move the `Tell` operation over to the actor Context.

e.g.

```go
//instead of 
pid.Tell(msg)
```

```go
//we would instead have
ctx.Tell(pid, msg)
```

This would allow us to build things like tracing using e.g. Zipkin.
It would also greatly simplyfy having multiple actor systems running at the same time. e.g. for parallel testing.

ctx would then be like a phone and the PID would just be the phone number.
Currently PID is both.

This would be a major breaking change, so I'm not completely sold on this idea myself, but I do see the added value it brings

**Comment by rogeralsing** [comment]
If we go for this approach, we also need to solve how to talk to PID's from outside an actor.
this could be done by having a `Tell` func directly in `actor`

```
actor.Tell(pid, msg)
```

That would be a "contextless" Tell.
If you have some sort of context, for example Zipkin data, and you want to call into the actor world using this context.
We could have something like this:

```
ctx := actor.NewRootContext( whatever context data)
ctx. Tell(pid, msg)
```

I think this would be fairly clean, even if this approach is more verbose than what we have currently.

**Comment by cpx86** [comment]
I'm not too familiar with how the context and PID interact yet, but from a user perspective I think it's important that there are as few ways as possible of doing something, preferably just one if possible.

Would it be a bad coupling if the PID knew about the context it belongs to? So calling `pid.Tell` would notify the context of the Tell operation, so it can do tracing or whatever it is it needs to do.

**Comment by rogeralsing** [comment]
Discussed API:

`context.Tell(pid, message)`

Related tasks

* Introducing a message envelope type carrying message headers.
* Introduce way of reading message headers from actor Context
* Introduce outbound middleware allowing code to read from actor context and write to outgoing message headers

**Comment by kempjeng** [comment]
have you considered

```go
func (c Ctx) Tell(pid *PID, message interface{}) {
    if msg, ok := message.(Message) {
      c.tellMessage(pid, msg)
    }
    c.tellMessage(pid, Message{Object: message})
}
````

Pros:
  * flexibility of telling with a simple message, or with additional details in the headers with a small API surface


Cons:
 * not discover-able from IDE


Additionally, I'd remove the helper Tell from PID and keep it as a DTO (functional style) rather than have two different methods to achieve the same operations as cpx86 suggested.

Have you considered changing `Message.Object` to `Message.Body`?  I feel it's more descriptive.
