### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by sterchelen** [AsynkronIT/protoactor-go#72]
Hi everyone,

My name is Nicolas, I'm a french .NET/python programmer. And for about 3 weeks a little Go programmer.

I would like to know if it's possible to contribute to the project ? 

Thank you.

**Comment by rogeralsing** [comment]
We have added a contributing.md for this: https://github.com/AsynkronIT/protoactor-go/blob/dev/CONTRIBUTING.md

That is more on a technical level though.
Depending on what you would like to do, there are a few things that could use some more attention.

The Go library is pretty active right now, the .NET port could use some extra contributors to get up to the same level as the Go version.

And if you are experienced in Python, you can always help lay the foundation for such port also.
