### ISSUE TITLE
mailbox.New*Producer

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#78]
IMO, we should rething the naming on the new mailbox package.
`props.WithMailbox(mailbox.NewUnboundedProducer())`

This reads a bit strange to me, not sure what would be better though.
`props.WithMailbox(mailboxUnboundedProducer())`
`props.WithMailbox(mailbox.NewUnbounded())`
`props.WithMailbox(mailbox.Unbounded())`

Or just stick with what we have?

**Comment by stuartcarnie** [comment]
I like the last

`props.WithMailbox(mailbox.Unbounded())`

**Comment by rogeralsing** [comment]
Fixed
